name: Run algo script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run login script
      env:
        API_KEY: ${{ secrets.API_KEY }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
        FEED_TOKEN: ${{ secrets.FEED_TOKEN }}
        SYMBOL_SHEET_URL: ${{ secrets.SYMBOL_SHEET_URL }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
        SHEET_NAME: ${{ secrets.SHEET_NAME }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python algo_login_and_run.py
